services:
  - type: web
    name: multimodal-saas-api
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /api/v1/health
    region: ohio
    envVars:
      - key: PORT
        value: 8000
    # Add any extra ENVs below if needed like secrets
